stages:
  - format
  - lint
  - test

variables:
  MIX_ENV: test

image:
  name: elixir:latest
  pull_policy: always

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - _build/
    - deps/

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

format_check:
  stage: format
  script:
    - mix format --check-formatted
  only:
    - merge_requests
    - master

lint:
  stage: lint
  script:
    - mix credo --strict
  only:
    - merge_requests
    - master

test:
  stage: test
  script:
    - mix test
  only:
    - merge_requests
    - master
