name: Elixir CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  elixir_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.7'
          otp-version: '26.0'
          version-type: 'loose'

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Format
        run: |
          mix format --check-formatted

      - name: Lint
        run: |
          mix credo --strict

      - name: Test with Coverage
        run: |
          mix coveralls --umbrella

      - name: Post Coverage to Coveralls
        run: |
          mix coveralls.github

      - name: Test
        run: |
          mix test
